#!/usr/bin/env python
import SCons.Script

# Define the GlobRecursive function
def GlobRecursive(pattern, node='.'):
    results = []
    for f in Glob(str(node) + '/*', source=True):
        if type(f) is SCons.Node.FS.Dir:
            results += GlobRecursive(pattern, f)
    results += Glob(str(node) + '/' + pattern, source=True)
    return results

# Import SCons and create the base environment
env = SConscript("godot-cpp/SConstruct")

# Add include directories to the environment
env.Append(CPPPATH=["include"])

# Glob all source files recursively in the src folder
sources = GlobRecursive('*.cpp', node='src')

# Create shared library
library = env.SharedLibrary(
    "bin/rgn{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

# Install the built library
install_targets = env.Install(env.Dir("../demo/addons/rgn/bin"), library)

# Set default targets
Default(install_targets)